version: '3.8'
services:
  bid-app-dev:
    build: .
    container_name: bid-app-dev
    ports: ["8002:8000"]
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
  
  bid-app-staging:
    image: ghcr.io/mahanthlbs/bid-system:staging-latest
    container_name: bid-app-staging
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=staging
    restart: unless-stopped
  
  bid-app-prod:
    image: ghcr.io/mahanthlbs/bid-system:prod-latest
    container_name: bid-app-prod
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
